### ISSUE TITLE
Roadmap for the next 4 months

### ISSUE THREAD

**Issue by Suhaas0079** [Suhaas0079/DS#1]
- [x] #2
- [x] #3
- [x] #4

**Comment by Suhaas0079** [comment]
- [ ] Fetch the resources 
- [ ] Fetch project ideas
- [ ] Create a road map
